server:
  port:8080

spring:
  application:
    name: Security-jwt
  security:
    user:
      name: user
      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vegetablesale?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    开启驼峰命名和下划线命名的自动转换
    map-underscore-to-camel-case: true